version: '3'

# There should be an environment variable called SLACK_URL

services:
    uptime:
        build:
            context: .
        image: bisq:uptime
        environment:
          - SLACK_URL
#    uptime-entropy:
#      restart: always
#     image: harbur/haveged:1.7c-1
#     container_name: haveged-entropy
#     privileged: true
