version: '2'

# There should be an environment variable called SLACK_URL

services:
    uptime:
        build:
            context: .
        image: bisq:uptime
        container_name: uptime
        ports:
          - 8080
        environment:
          - SLACK_PRICE_URL
          - SLACK_SEED_URL
          - SLACK_BTC_URL

